### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by pea3nut** [pea3nut/pea3nut-hub#1]
- [x] 在 script 里面的脚本，增加 set -e
- [x] 在 package 脚本中，设置端口号
- [x] 在 package 脚本中，打印端口号和ip
